#[allow(dead_code)]
pub enum ResponseCodes {
    ResponseSuccess = 0x00,
    ResponseFailure = 0x01,
    ResponseCancelled = 0x02,
    ResponseDisconnected = 0x03,
    ResponseFailedToConnect = 0x04,
    ResponseConnected = 0x05,
    ResponseVersionMismatch = 0x06,

    CstatusConnecting = 0x07,
    CstatusNegotiatingSecurity = 0x08,
    CstatusNegotiationComplete = 0x09,
    CstatusNegotiationFailed = 0x0A,
    CstatusAuthenticating = 0x0B,

    AuthOk = 0x0C,
    AuthFailed = 0x0D,
    AuthReject = 0x0E,
    AuthBadServerProof = 0x0F,
    AuthUnavailable = 0x10,
    AuthSystemError = 0x11,
    AuthBillingError = 0x12,
    AuthBillingExpired = 0x13,
    AuthVersionMismatch = 0x14,
    AuthUnknownAccount = 0x15,
    AuthIncorrectPassword = 0x16,
    AuthSessionExpired = 0x17,
    AuthServerShuttingDown = 0x18,
    AuthAlreadyLoggingIn = 0x19,
    AuthLoginServerNotFound = 0x1A,
    AuthWaitQueue = 0x1B,
    AuthBanned = 0x1C,
    AuthAlreadyOnline = 0x1D,
    AuthNoTime = 0x1E,
    AuthDbBusy = 0x1F,
    AuthSuspended = 0x20,
    AuthParentalControl = 0x21,
    AuthLockedEnforced = 0x22,

    RealmListInProgress = 0x23,
    RealmListSuccess = 0x24,
    RealmListFailed = 0x25,
    RealmListInvalid = 0x26,
    RealmListRealmNotFound = 0x27,

    AccountCreateInProgress = 0x28,
    AccountCreateSuccess = 0x29,
    AccountCreateFailed = 0x2A,

    CharListRetrieving = 0x2B,
    CharListRetrieved = 0x2C,
    CharListFailed = 0x2D,

    CharCreateInProgress = 0x2E,
    CharCreateSuccess = 0x2F,
    CharCreateError = 0x30,
    CharCreateFailed = 0x31,
    CharCreateNameInUse = 0x32,
    CharCreateDisabled = 0x33,
    CharCreatePvpTeamsViolation = 0x34,
    CharCreateServerLimit = 0x35,
    CharCreateAccountLimit = 0x36,
    CharCreateServerQueue = 0x37,
    CharCreateOnlyExisting = 0x38,
    CharCreateExpansion = 0x39,

    CharDeleteInProgress = 0x3A,
    CharDeleteSuccess = 0x3B,
    CharDeleteFailed = 0x3C,
    CharDeleteFailedLockedForTransfer = 0x3D,
    CharDeleteFailedGuildLeader = 0x3E,
    CharDeleteFailedArenaCaptain = 0x3F,

    CharLoginInProgress = 0x40,
    CharLoginSuccess = 0x41,
    CharLoginNoWorld = 0x42,
    CharLoginDuplicateCharacter = 0x43,
    CharLoginNoInstances = 0x44,
    CharLoginFailed = 0x45,
    CharLoginDisabled = 0x46,
    CharLoginNoCharacter = 0x47,
    CharLoginLockedForTransfer = 0x48,
    CharLoginLockedByBilling = 0x49,

    CharNameSuccess = 0x4A,
    CharNameFailure = 0x4B,
    CharNameNoName = 0x4C,
    CharNameTooShort = 0x4D,
    CharNameTooLong = 0x4E,
    CharNameInvalidCharacter = 0x4F,
    CharNameMixedLanguages = 0x50,
    CharNameProfane = 0x51,
    CharNameReserved = 0x52,
    CharNameInvalidApostrophe = 0x53,
    CharNameMultipleApostrophes = 0x54,
    CharNameThreeConsecutive = 0x55,
    CharNameInvalidSpace = 0x56,
    CharNameConsecutiveSpaces = 0x57,
    CharNameRussianConsecutiveSilentCharacters = 0x58,
    CharNameRussianSilentCharacterAtBeginningOrEnd = 0x59,
    CharNameDeclensionDoesntMatchBaseName = 0x5A,
}
