ALTER TABLE characters ADD COLUMN current_mana INTEGER NOT NULL DEFAULT 0;
ALTER TABLE characters ADD COLUMN current_rage INTEGER NOT NULL DEFAULT 0;
ALTER TABLE characters ADD COLUMN current_energy INTEGER NOT NULL DEFAULT 0;
