ALTER TABLE characters ADD COLUMN map_id INTEGER NOT NULL DEFAULT 0.0;
ALTER TABLE characters ADD COLUMN zone_id INTEGER NOT NULL DEFAULT 0.0;
ALTER TABLE characters ADD COLUMN position_x REAL NOT NULL DEFAULT 0.0;
ALTER TABLE characters ADD COLUMN position_y REAL NOT NULL DEFAULT 0.0;
ALTER TABLE characters ADD COLUMN position_z REAL NOT NULL DEFAULT 0.0;
ALTER TABLE characters ADD COLUMN orientation REAL NOT NULL DEFAULT 0.0;
