[package]
name = "rustbolt-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.1"
tokio = { version = "1", features = ["full"] }
wow_srp = "0.5.3"
