[common]
[common.data]
directory = "./data"

[auth]
[auth.network]
host = "127.0.0.1"
port = "3724"

[world]
[world.network]
host = "127.0.0.1"
port = "8085"

[world.game]
target_tick_time_ms = 50

[world.game.player]
maxlevel = 70

[world.dev]
load_terrain = true
load_creature_templates = true
load_game_object_templates = true
