PRAGMA foreign_keys=OFF;
CREATE TABLE IF NOT EXISTS "quest_templates" (
  "entry" mediumint(8)  NOT NULL DEFAULT '0',
  "method" tinyint(3)  NOT NULL DEFAULT '2',
  "zone_or_sort" smallint(6) NOT NULL DEFAULT '0',
  "min_level" tinyint(3)  NOT NULL DEFAULT '0',
  "level" smallint(6) NOT NULL DEFAULT '0',
  "type" smallint(5)  NOT NULL DEFAULT '0',
  "required_classes" smallint(5)  NOT NULL DEFAULT '0',
  "required_races" smallint(5)  NOT NULL DEFAULT '0',
  "required_skill" smallint(5)  NOT NULL DEFAULT '0',
  "required_skill_value" smallint(5)  NOT NULL DEFAULT '0',
  "rep_objective_faction" smallint(5)  NOT NULL DEFAULT '0',
  "rep_objective_value" mediumint(9) NOT NULL DEFAULT '0',
  "required_min_rep_faction" smallint(5)  NOT NULL DEFAULT '0',
  "required_min_rep_value" mediumint(9) NOT NULL DEFAULT '0',
  "required_max_rep_faction" smallint(5)  NOT NULL DEFAULT '0',
  "required_max_rep_value" mediumint(9) NOT NULL DEFAULT '0',
  "suggested_players" tinyint(3)  NOT NULL DEFAULT '0',
  "time_limit" int(10)  NOT NULL DEFAULT '0',
  "flags" smallint(5)  NOT NULL DEFAULT '0',
  "special_flags" tinyint(3)  NOT NULL DEFAULT '0',
  "character_title" tinyint(3)  NOT NULL DEFAULT '0',
  "previous_quest_id" mediumint(9) NOT NULL DEFAULT '0',
  "next_quest_id" mediumint(9) NOT NULL DEFAULT '0',
  "exclusive_group" mediumint(9) NOT NULL DEFAULT '0',
  "next_quest_in_chain" mediumint(8)  NOT NULL DEFAULT '0',
  "source_item_id" mediumint(8)  NOT NULL DEFAULT '0',
  "source_item_count" tinyint(3)  NOT NULL DEFAULT '0',
  "source_spell" mediumint(8)  NOT NULL DEFAULT '0',
  "title" text DEFAULT NULL,
  "details" text DEFAULT NULL,
  "objectives" text DEFAULT NULL,
  "offer_reward_text" text DEFAULT NULL,
  "request_items_text" text DEFAULT NULL,
  "end_text" text DEFAULT NULL,
  "objective_text1" text DEFAULT NULL,
  "objective_text2" text DEFAULT NULL,
  "objective_text3" text DEFAULT NULL,
  "objective_text4" text DEFAULT NULL,
  "required_item_id1" mediumint(8)  NOT NULL DEFAULT '0',
  "required_item_id2" mediumint(8)  NOT NULL DEFAULT '0',
  "required_item_id3" mediumint(8)  NOT NULL DEFAULT '0',
  "required_item_id4" mediumint(8)  NOT NULL DEFAULT '0',
  "required_item_count1" smallint(5)  NOT NULL DEFAULT '0',
  "required_item_count2" smallint(5)  NOT NULL DEFAULT '0',
  "required_item_count3" smallint(5)  NOT NULL DEFAULT '0',
  "required_item_count4" smallint(5)  NOT NULL DEFAULT '0',
  "required_source_item_id1" mediumint(8)  NOT NULL DEFAULT '0',
  "required_source_item_id2" mediumint(8)  NOT NULL DEFAULT '0',
  "required_source_item_id3" mediumint(8)  NOT NULL DEFAULT '0',
  "required_source_item_id4" mediumint(8)  NOT NULL DEFAULT '0',
  "required_source_item_count1" smallint(5)  NOT NULL DEFAULT '0',
  "required_source_item_count2" smallint(5)  NOT NULL DEFAULT '0',
  "required_source_item_count3" smallint(5)  NOT NULL DEFAULT '0',
  "required_source_item_count4" smallint(5)  NOT NULL DEFAULT '0',
  "required_entity_id1" mediumint(9) NOT NULL DEFAULT '0',
  "required_entity_id2" mediumint(9) NOT NULL DEFAULT '0',
  "required_entity_id3" mediumint(9) NOT NULL DEFAULT '0',
  "required_entity_id4" mediumint(9) NOT NULL DEFAULT '0',
  "required_entity_count1" smallint(5)  NOT NULL DEFAULT '0',
  "required_entity_count2" smallint(5)  NOT NULL DEFAULT '0',
  "required_entity_count3" smallint(5)  NOT NULL DEFAULT '0',
  "required_entity_count4" smallint(5)  NOT NULL DEFAULT '0',
  "required_spell_cast1" mediumint(8)  NOT NULL DEFAULT '0',
  "required_spell_cast2" mediumint(8)  NOT NULL DEFAULT '0',
  "required_spell_cast3" mediumint(8)  NOT NULL DEFAULT '0',
  "required_spell_cast4" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_choice_item_id1" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_choice_item_id2" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_choice_item_id3" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_choice_item_id4" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_choice_item_id5" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_choice_item_id6" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_choice_item_count1" smallint(5)  NOT NULL DEFAULT '0',
  "reward_choice_item_count2" smallint(5)  NOT NULL DEFAULT '0',
  "reward_choice_item_count3" smallint(5)  NOT NULL DEFAULT '0',
  "reward_choice_item_count4" smallint(5)  NOT NULL DEFAULT '0',
  "reward_choice_item_count5" smallint(5)  NOT NULL DEFAULT '0',
  "reward_choice_item_count6" smallint(5)  NOT NULL DEFAULT '0',
  "reward_item_id1" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_item_id2" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_item_id3" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_item_id4" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_item_count1" smallint(5)  NOT NULL DEFAULT '0',
  "reward_item_count2" smallint(5)  NOT NULL DEFAULT '0',
  "reward_item_count3" smallint(5)  NOT NULL DEFAULT '0',
  "reward_item_count4" smallint(5)  NOT NULL DEFAULT '0',
  "reward_rep_faction1" smallint(5)  NOT NULL DEFAULT '0',
  "reward_rep_faction2" smallint(5)  NOT NULL DEFAULT '0',
  "reward_rep_faction3" smallint(5)  NOT NULL DEFAULT '0',
  "reward_rep_faction4" smallint(5)  NOT NULL DEFAULT '0',
  "reward_rep_faction5" smallint(5)  NOT NULL DEFAULT '0',
  "reward_rep_value1" mediumint(9) NOT NULL DEFAULT '0',
  "reward_rep_value2" mediumint(9) NOT NULL DEFAULT '0',
  "reward_rep_value3" mediumint(9) NOT NULL DEFAULT '0',
  "reward_rep_value4" mediumint(9) NOT NULL DEFAULT '0',
  "reward_rep_value5" mediumint(9) NOT NULL DEFAULT '0',
  "reward_honorable_kills" int(10)  NOT NULL DEFAULT '0',
  "required_or_reward_money" int(11) NOT NULL DEFAULT '0',
  "reward_money_max_level" int(10)  NOT NULL DEFAULT '0',
  "reward_spell" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_spell_cast" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_mail_template_id" mediumint(8)  NOT NULL DEFAULT '0',
  "reward_mail_delay_seconds" int(11)  NOT NULL DEFAULT '0',
  "point_map_id" smallint(5)  NOT NULL DEFAULT '0',
  "point_x" float NOT NULL DEFAULT '0',
  "point_y" float NOT NULL DEFAULT '0',
  "point_opt" mediumint(8)  NOT NULL DEFAULT '0',
  "details_emote1" smallint(5)  NOT NULL DEFAULT '0',
  "details_emote2" smallint(5)  NOT NULL DEFAULT '0',
  "details_emote3" smallint(5)  NOT NULL DEFAULT '0',
  "details_emote4" smallint(5)  NOT NULL DEFAULT '0',
  "details_emote_delay1" int(11)  NOT NULL DEFAULT '0',
  "details_emote_delay2" int(11)  NOT NULL DEFAULT '0',
  "details_emote_delay3" int(11)  NOT NULL DEFAULT '0',
  "details_emote_delay4" int(11)  NOT NULL DEFAULT '0',
  "incomplete_emote" smallint(5)  NOT NULL DEFAULT '0',
  "complete_emote" smallint(5)  NOT NULL DEFAULT '0',
  "offer_reward_emote1" smallint(5)  NOT NULL DEFAULT '0',
  "offer_reward_emote2" smallint(5)  NOT NULL DEFAULT '0',
  "offer_reward_emote3" smallint(5)  NOT NULL DEFAULT '0',
  "offer_reward_emote4" smallint(5)  NOT NULL DEFAULT '0',
  "offer_reward_emote_delay1" int(11)  NOT NULL DEFAULT '0',
  "offer_reward_emote_delay2" int(11)  NOT NULL DEFAULT '0',
  "offer_reward_emote_delay3" int(11)  NOT NULL DEFAULT '0',
  "offer_reward_emote_delay4" int(11)  NOT NULL DEFAULT '0',
  PRIMARY KEY ("entry")
);
